### ISSUE TITLE
Fix protocol

### ISSUE THREAD

**Issue by bkircher** [swojtasiak/jsrdbg#16]
During implementation of [vscode-janus-debug](https://github.com/otris/vscode-janus-debug), a VS Code debug client that uses jsrdbg as a debugging engine, we found several issues in the protocol that make it hard to write concise and, more importantly, correct client-side code.

For instance:

Req: `"get_available_contexts\n"`
This is a request that produces a response that a client obviously needs to get all curently known JSContexts. Since the client cannot send an "id" along with the request, the response produced by the server contains none.
Res: `"{"type":"info","subtype":"contexts_list","contexts":[{"contextId":0,"contextName":"example-JS","paused":true}]}"`
This tends to make client code a pain to write because it cannot associate the response coming in to the request send out earlier. This is especially the case when the client code is highly asynchronous.

`"server_version\n"` (added by us, so we are guilty here ourselves) suffers from the same issue.

Suggestion: we could actually just use [JSON-RPC](http://www.jsonrpc.org/specification) rigorously. It is already very similar to what we have in jsrdbg and a lot of people out there are familiar with how it works. Changing the existing protocol in libjsrdbg and jrdb should be possible without a major re-write. Also on the plus-side: there might already be libraries out there that clients could use to make use of the protocol.

**Comment by swojtasiak** [comment]
I'll take a look at JSON-RPC specification. If I remember correctly I've already used it somewhere, but I don't remember details now. If JSON-RPC specifies something like (tracking codes) then we can of course use it, standardisation has variety of benefits. I'll try to take a look at it in next 2-3 days. As a workaround we can probably add "id" support to these non JSON compliant requests - I'll check the code and consider that.

**Comment by swojtasiak** [comment]
Take a look at this PR: [https://github.com/swojtasiak/jsrdbg/pull/17](https://github.com/swojtasiak/jsrdbg/pull/17)

It adds request ID support for non JSON commands like contexts_list and server_version. It should be enough for now to pair such requests with their responses.

We can make the protocol JSON-RPC compliant in the future, but unfortunately I do not have time for that now.

Btw. The only reason why system commands are not encoded using JSON is because I didn't want to add external JSON parser to C++ code just to parse two or three parameter less commands. If we would like to add JSON-RPC support in the future we'll have to include it anyway, just to make all the commands JSON-RPC compliant.

**Comment by bkircher** [comment]
> Btw. The only reason why system commands are not encoded using JSON is because I didn't want to add external JSON parser to C++ code just to parse two or three parameter less commands.

I see. Makes sense.

Thanks for the PR!
