### ISSUE TITLE
Commands not processed when no script is executing

### ISSUE THREAD

**Issue by ursmanoj** [swojtasiak/jsrdbg#18]
First of all, thanks for this awesome implementation, really helped me a lot.
I have a specific use case in my experimental project.
- Set breakpoint when no script is executing (similar other operations as well, this being most important).
- JSRDBG queues this, but real breakpoint is set only after a script is executed in given context.
- Thus a script developer cannot 
     -> First set a breakpoint
     -> Then execute the script.

Please guide which part of JSRDBG code I have to change in order to have desired behaviour.

Thanks in advance.
Manoj

**Comment by swojtasiak** [comment]
Hi Manoj,

I'm glad that you like the project. Unfortunately I don't remember all the details so I have to take a look at it in my free time and remind myself how it exactly works. I'll try to do it as soon as possible.

Regards,

**Comment by ursmanoj** [comment]
Yes please. Or if you had made some internal architecture document which can be shared. Then I will have some pointers on which part of code I should look into for desired modifications.
Thanks again.

**Comment by swojtasiak** [comment]
I've just extended example project a bit just to make it more useful when it comes to debugging and I think I've managed to replicate the problem, so I'll take a look at it in the next days. Unfortunately there is nothing like an architectural document at the moment. If time allows me I'll try to prepare some diagrams, but taking into account that it took me about two weeks to find time for this problem, it can take time.

**Comment by swojtasiak** [comment]
https://github.com/swojtasiak/jsrdbg/pull/21

**Comment by swojtasiak** [comment]
I've added a way to fix the problem you described. Unfortunately the solution is not so obvious and needs user action.

The source of the problem is that in order to handle debugger commands the library has to have control over the thread that is used to run the engine. The only way to do that transparently is to ask SpiderMonkey to run the piece of code that runs pending commands on its own thread. 

 This function is responsible for executing queued commands: https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/src/js_remote_dbg.cpp#L79

We have two cases where we can do that. The first one is quite obvious and it works very well. It's when script is paused by the debugger and debugger has the full control over the engine.

https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/src/js/mozjs_dbg.js#L1128

The second one is a bit more problematic, because we have to prompt the engine to run debugger specific code when script is not paused and there are pending commands in the queue. In order to do so we use the following callback:

https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/src/js_remote_dbg.cpp#L581

It calls the following function which runs command loop responsible for calling pending commands:

https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/src/js_remote_dbg.cpp#L196

The callback is called periodically by the engine when script runs, but we do not have any control over when it's called. I mentioned the problem in this article: https://wiki.gnome.org/Projects/GnomeShell/DebuggingJavaScript. The callback tends to be called just before a new script is run on the engine, but in your case it probably isn't invoked. Unfortunately it's hard to tell why, as we cannot control this callback. 

I decided to give user a way to ask debugger to handle pending commands if there are any. It can be done by calling the following method on the same thread that runs the engine. User controls this thread so it's not a big deal.

https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/public/jsrdbg.h#L227

In your case it can be called just before the script is run. After breakpoints are added to the command queue but just before the script is run. In such a way you will force the debugger to "flush" them before the engine starts executing the script. Here is an example:

https://github.com/swojtasiak/jsrdbg/blob/0c8022526bb97c34b2f4ce1c82749883b21e8906/example/src/main.cpp#L224

Let me know if it helps.
